# Generated by Django 4.0 on 2024-07-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0002_photo_service_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='best_offer',
            field=models.BooleanField(default=False),
        ),
    ]
